import psutil

# for process in psutil.process_iter():
#     print(process)
#     print("*"*60)
# print((((psutil.boot_time()/1000)/60)/60)/24)
# print(psutil.cpu_count(logical=True))
# print(psutil.cpu_freq(percpu=True))
# print(psutil.cpu_percent(percpu=True))
# print(psutil.cpu_stats())
# print(psutil.cpu_times())
# print(psutil.cpu_times_percent(percpu=True))
# print(psutil.disk_io_counters(perdisk=True,nowrap=True))
# print(psutil.disk_partitions(all=True))
# print(psutil.disk_usage("D:\Web_And_App_Development\Python Programming Tutorials\System Viewer in Python"))
# print(psutil.getloadavg())
# print(psutil.net_connections())
# print(psutil.net_if_addrs())
# print(psutil.net_if_stats())
# print(psutil.net_io_counters())
# print(psutil.pid_exists(56))
# print(psutil.pids())
# print(psutil.swap_memory())
# print(psutil.users())
# print(psutil.version_info)
# print(psutil.win_service_iter())